sudo: false

language: node_js
matrix:
  include:
    - node_js: '5'
    - node_js: '4'
    - node_js: '0.12'
      env: NO_ESLINT=true

script: "[[ $NO_ESLINT == true ]] && npm run test-012 || npm test"
